added custom login theme
bcgov/social-access-portal pull request #22
Opened 2022-06-06 18:39 UTC by roy-sagar11

## Summary
Added custom login page in keycloak

## Changes

## Screenshots (if applicable)

<img width="1440" alt="Screen Shot 2022-06-06 at 12 18 33 PM" src="https://user-images.githubusercontent.com/83042102/172225104-38c7b138-588f-4e13-a7ac-6cc1564c0856.png">

## Notes

2022-06-06 19:36 UTC, simensma-fresh requested changes
Looks good! Just a couple of changes we'll need to match the existing `bcgov-idp-stopper` theme.

We'll also need to change the `login_theme`s in our tf config from `bcgov-idp-stopper` to `ssag` to apply this in dev

2022-06-06 19:36 UTC, simensma-fresh commented on keycloak/extensions/themes/src/main/resources/theme/ssag/login/template.ftl
> +  </div>
I'm wondering if we could add in a couple of the other missing sections here as well from https://github.com/keycloak/keycloak/blob/9c01d819cb8d1709503e61db62f630686d5a1c5e/themes/src/main/resources/theme/base/login/template.ftl:
- Error/warning section:
- "Try another way link" 
- "Displayinfo"

2022-06-06 19:36 UTC, simensma-fresh commented on keycloak/extensions/themes/src/main/resources/theme/ssag/login/template.ftl
> +        <#nested "socialProviders">
Could we do something similar to https://github.com/bcgov/social-access-portal/blob/main/keycloak/theme/bcgov-idp-stopper/login/login.ftl here? As the `login.username?contains("##" + p.alias + "##")` determines what identity providers should show up as set in https://github.com/bcgov/social-access-portal/blob/main/keycloak/extensions/services/src/main/java/com/github/bcgov/keycloak/authenticators/browser/IdentityProviderStopForm.java

2022-06-06 20:01 UTC, iman-jamali-fw commented on keycloak/extensions/themes/src/main/resources/theme/ssag/login/resources/css/styles.css
> +}
Not sure how much value it adds, but it is possible to add one font-face with multiple weights and styles. Please see [here](https://stackoverflow.com/questions/28279989/multiple-font-weights-one-font-face-query). Feel free to try if that seems reasonable for this project.

2022-06-06 20:04 UTC, iman-jamali-fw approved these changes
LGTM

2022-06-06 20:43 UTC, roy-sagar11 commented on keycloak/extensions/themes/src/main/resources/theme/ssag/login/resources/css/styles.css
> +}
good point. will do that!

2022-06-07 18:02 UTC, iman-jamali-fw commented on keycloak/extensions/themes/src/main/resources/theme/bcgov/login/resources/css/styles.css
> +}
Looks great!

2022-06-07 18:09 UTC, iman-jamali-fw approved these changes
Changes look good to me

2022-06-07 18:22 UTC, simensma-fresh approved these changes

2022-06-07 18:30 UTC, merged