[WIP] terraform test setup
bcgov/social-access-portal pull request #6
Opened 2022-05-20 04:38 UTC by roy-sagar11

## Summary

## Changes

## Screenshots (if applicable)

## Notes

2022-05-20 15:20 UTC, simensma-fresh requested changes
Looks great! Just two small comments

2022-05-20 15:20 UTC, simensma-fresh commented on terraform/values.yaml
> +  tag: "latest"
Can we change this to `18.0.0`? Just want to make sure it doesn't auto-upgrade seeing as KeyCloak upgrades usually require some downtime

2022-05-20 15:20 UTC, simensma-fresh commented on terraform/values.yaml
> +livenessProbe: {}
I'm wondering if we can reenable the liveness/readiness/startup probes now that we know the config is working :)

2022-05-20 15:36 UTC, iman-jamali-fw approved these changes
Great work @roy-sagar11.

Sorry, I just started to learn Kubernetes and Terraform and cannot help much in this pr but learned a lot by reading it. Thanks

2022-05-24 17:42 UTC, simensma-fresh approved these changes

2022-05-26 17:13 UTC, merged